#!/bin/bash 
. ${0%/*}/ENV.setview   # Environment

export TLA=${TLA:-$HOME/bin/tla}

if [[ ! -d {arch} ]]
then
   echo "Error: This directory is not associated with an archive."
   echo "Please run mkview -a ? -c ? --baseline to set it up."
   exit 1
fi

$TLA inventory --names --both --source  | xargs $TLA add-id

log=$($TLA make-log 2>/dev/null)

echo "Import baseline the view $(basename $(pwd))." >> "$log";

$TLA import
