#!/bin/bash
# Shell script to list local views into existing archive projects
. ${0%/*}/ENV.setview   # Environment

GIT=${GIT:-$HOME/bin/tla}
STDSOURCETREEROOT=${HOME}/{views}
SOURCETREEROOT=${SOURCETREEROOT:-$STDSOURCETREEROOT}
export GIT SOURCETREEROOT
export VIEWMAXDEPTH=7

function listviews() 
{
if [[ "$1" = "-l" ]]
then
   find $SOURCETREEROOT -maxdepth $VIEWMAXDEPTH -mindepth 1  -follow -type d -name {arch} -not -path */{arch}/* -printf "%h\n"
elif [[ "$1" = "-m" ]]
then
   cd $SOURCETREEROOT
   find . -maxdepth $VIEWMAXDEPTH -mindepth 1  -follow -type d -name {arch} -not -path */{arch}/* -printf "%h\n" | while read name
   do
      fpart=$(basename $name)
      dirpart=${name##\./}
      dirpart=${dirpart%%/*}
      echo "$dirpart	~/$fpart"
   done
else
   find $SOURCETREEROOT -maxdepth $VIEWMAXDEPTH -mindepth 1  -follow -type d -name {arch} -not -path */{arch}/* -printf "%h\n" | while read name 
   do
      basename $name 
   done
fi
}

listviews $*
