#!/bin/bash
# Mirror a local archive to a local web-accessible directory
. ${0%/*}/ENV.setview   # Environment

WEBMIRRORSDIR=/var/www/html/mirrors/
TLA=${TLA:-$HOME/bin/tla}
export TLA

if [[ -z "$1" ]]
then
   select name in $($TLA archives --names 2>&1; echo "Quit")
   do 
      if [[ ! -z "$name" ]]
      then
         newdefault="$name";
         break;
      else
         echo "The selection you made is not an option. Quitting..."
	 exit
      fi
   done
else
   newdefault="$1"
fi

if [[ "$newdefault" = "Quit" ]]
then
   exit;
fi

mirrordir=$WEBMIRRORSDIR/${newdefault##*-}

$TLA make-archive --listing --mirror $newdefault $mirrordir
$TLA archive-mirror $newdefault
