#!/bin/bash
# Shell script to create a log for a source tree prior to commit
# to avoid overwriting a log and having to recall the editor commands to edit 
. ${0%/*}/ENV.setview   # Environment

editor=${EDITOR:-/bin/vi}

function fusage()
{
   if [[ ! -z "$1" ]]
   then
      echo $1
   fi
   /bin/cat <<EOT
   mklog: create a log for a source tree prior to commit
   Synopsis:
      mklog [-h] [-n|-q]

      Executed without arguments, mklog creates a log for the current source
      tree and invokes the editor in \$EDITOR to edit the log.

      If no default archive is set and none is specified, mklog does nothing.

      If -q option is set, mklog invokes "echo" instead of the editor.
      If -n option is set, mklog only checks and prints the arguments.

      This script uses the environmental variable \$TLAarchive, as set 
      by the "setview" script.
EOT
}

if [[ "$1" = "-h" ]]
then
   fusage
fi

   # Check to see if we are running in a view
typeset -F tla >/dev/null
if [[ -z "$TLAarchive" || $? == 1 ]]
then
   fusage "TLAarchive variable not set. The script was not invoked\nfrom a view, so it is bailing out."
fi

if [[ "$1" = "-n" ]]
then
   editor="/bin/echo"
fi

if [[ "$1" = "-q" ]]
then 
   /bin/echo "$editor \$(tla make-log)"
else
      # make the log and invoke the editor (or echo)
   "$editor" $(tla make-log)
fi
