#!/bin/bash
# Shell script to push and pop a default archive for a new command shell
. ${0%/*}/ENV.setview   # Environment
export TLA=${TLA:-$HOME/bin/tla}

if [[ -z "$1" ]]
then
   select name in $($TLA archives --names 2>&1; echo "Quit")
   do 
      if [[ ! -z "$name" ]]
      then
         newdefault="$name";
         break;
      else
         echo "The selection you made is not an option. Quitting..."
	 exit
      fi
   done
else
   newdefault="$1"
fi

if [[ "$newdefault" = "Quit" ]]
then
   exit;
fi

currentarchive=$($TLA my-default-archive 2>&1)
if [[ "$currentarchive" != "my-default-archive: no default archive" ]]
then
   trap "$TLA my-default-archive '$currentarchive'" EXIT
else
   trap "$TLA my-default-archive --delete" EXIT
fi

prompt=${newdefault##*-}

(
   export PS1="$prompt: "

   $TLA my-default-archive "$newdefault"
   bash --login
)
