#!/bin/bash
. ${0%/*}/ENV.setview   # Environment

export TLA=${TLA:-$HOME/bin/tla}

$TLA help | grep : | cut -d: -f1 | while read a
do 
   if [[ $($TLA $a --help | grep -- "-A" |wc -l) -ne 1 ]] 
   then 
      echo $a
   fi
done
