#!/bin/bash
# Shell script to list local views into existing archive projects
. ${0%/*}/ENV.setview

TLA=${TLA:-$HOME/bin/tla}
STDSOURCETREEROOT=${HOME}/{views}
SOURCETREEROOT=${SOURCETREEROOT:-$STDSOURCETREEROOT}
export TLA SOURCETREEROOT


function fusage()
{
   echo "$msg"
   /bin/cat <<EOT
   setview view help

   Synopsis: 
      User scripts
      ------------
      importbaseline    import a source tree 
      mirrorlocal2localweb  copy a view to a local Web mirror
      mklog             make and edit a log prior to a commit
      mkview            create a new view
      newarchive        create a new archive
      setview           set the current view
      viewhelp          this file
      
      User Shell Functions (from setview.setup)
      --------------------
      listviews()   list the views
      listarchives()   list the registered archives
      inittree()  initialize a source tree w/ tla inventory + tla import
      tlacurry()  import tla "-a" subcommands as shell functions (slow)
      tlacurryall()  import all tla subcommands as shell functions (slow)
      tlacurryallfaster()   import list of subcommands (fast but not accurate)
      tla()    run tla with respect to the current view
      lcd()    change directory to \$VIEWHOME


      Scripts (useful outside of a view)
      -------
      listarchives      list archives
      listviews         list views
      setarchive        push and pop a default archive
EOT
}

while [[ ! -z "$1" ]]
do
   case $1 in
   *)
   ;;
   --debug) 
      export dbg="echo"
   ;;
   esac
   shift; # get rid of $1
done


fusage;
