#!/bin/bash
# This script is copied to a Windows PC on which Putty is loaded

# A Putty Private Key File will need to be created using Putty's user interface.
# The public key part should be copied into the $HOME/.ssh/authorized_keys 
# file under the Linux user account in which you will do work.

# On Windows, a command line like this:
# putty -m WinPuttyTreeLint -l loginname -ssh hostname -i puttyprivkey.ppk -t
#
# Should be put into a Windows shortcut or a batch file to allow you
# to invoke Arch commands with a double-click.
#
# WinPuttyTreeLint is this file; Putty will send it to the host for execution.
# It is a good idea to use %USERPROFILE% to locate the files in a location
# relative to your Windows profile.
# loginname is your user account name on the Linux host "hostname"
# puttyprivkey.ppk is the private key file created in Putty for which 
# the public key was copied to your Linux $HOME/.ssh/authorized_keys file.
#
# -t tells ssh to allocate a terminal device under Linux. Otherwise the
# output will not look right.
#
# You can also configure a Putty session with the same kinds of options -
# using the putty UI is quite a bit easier than using command line options.

# This example checks the status of the source tree in a setview view
setview -v archtools --exec "tla tree-lint" --pause "Hit Return To Close"

